# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'Follow on: 
        <a href="https://twitter.com/d4rk_wing" target="_blank"><img src="/images/twitter.png" alt="" width="20" height="20" /></a>
        <a href="https://github.com/d4rk-wing" target="_blank"><img src="/images/github.png" alt="" width="20" height="20" /></a>
        '

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
